@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1Njc3NTUwLCJpYXQiOjE3NTU2NzM5NTAsImp0aSI6ImY0YTBiZDc3ZTM5OTQwOTliNzZjOTc4MzRjMDQxNjQyIiwidXNlcl9pZCI6IjIifQ.26i2zcnhyrzsH9xG44UvU_LsUSKODGXGZFNHXJQjmJw
@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2NDQwNzEyLCJpYXQiOjE3NTY0MzcxMTIsImp0aSI6IjI0NTgwODFkZDEyODQ5YzM4N2ZjMzk2YjliNjVlMTJlIiwidXNlcl9pZCI6IjIifQ.jd6h_r_Q8dYhr4odHfJyfLUZAlYOLIligABbHcwMz5w
### ===== AUTHENTICATION =====
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "kurtamodia",
    "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "PASTE_REFRESH_TOKEN_HERE"
}

### ===== SKILLS =====
GET http://localhost:8000/api/skills/ HTTP/1.1

###
GET http://localhost:8000/api/skills/46/ HTTP/1.1

###
POST http://localhost:8000/api/skills/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
    "name": "Sword Dance",
    "element": "Light",
    "power": 120
}

###
PUT http://localhost:8000/api/skills/46/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}}}

{
    "name": "Ice Blast Plus",
    "element": "Water",
    "power": 85
}

###
DELETE http://localhost:8000/api/skills/46/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}


### ===== HUNTERS =====
GET http://localhost:8000/api/hunters/ HTTP/1.1

###
GET http://localhost:8000/api/hunters/2/ HTTP/1.1

###
POST http://localhost:8000/api/hunters/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
    "first_name": "Lightning", 
    "last_name": "McQueen", 
    "username": "speedy", 
    "password": "test", 
    "email": "speedy@gmail.com",
    "rank": "E",
    "skills": [],
    "guild": null
}

###

PATCH http://localhost:8000/api/hunters/6/
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "skills": [3]
}

###
PUT http://localhost:8000/api/hunters/39/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "first_name": "CJ", 
    "last_name": "Pingal", 
    "username": "cjpingal", 
    "password": "test",
    "email": "ping@example.com",
    "rank": "D",
    "skills": [50],
    "guild": null
}

###
DELETE http://localhost:8000/api/hunters/39/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}


### ===== GUILDS =====
GET http://localhost:8000/api/guilds/ HTTP/1.1

###
GET http://localhost:8000/api/guilds/10/ HTTP/1.1

###
POST http://localhost:8000/api/guilds/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
    "name": "Scavengers",
    "leader": 8
}

###
PUT http://localhost:8000/api/guilds/11/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "name": "Frost Wolves Elite",
    "leader": 23
}

###
DELETE http://localhost:8000/api/guilds/11/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}


### ===== GUILD INVITE =====
POST http://localhost:8000/api/guild-invite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "guild_id": 1,
    "hunter_id": 7
}


### ===== DUNGEONS =====
GET http://localhost:8000/api/dungeons/ HTTP/1.1

###
GET http://localhost:8000/api/dungeons/6/ HTTP/1.1

###
POST http://localhost:8000/api/dungeons/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
    "name": "Ant Cave",
    "location": "Jeju Island",
    "rank": "S",
    "is_open": true
}

###
PUT http://localhost:8000/api/dungeons/12/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "name": "Frozen Cavern Deep",
    "location": "North Mountains",
    "rank": "A"
}

###
DELETE http://localhost:8000/api/dungeons/12/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}


### ===== RAIDS =====
GET http://localhost:8000/api/raids/ HTTP/1.1

###
GET http://localhost:8000/api/raids/75f2c13e-2cc6-4f20-8e7a-315791a9790b/ HTTP/1.1

###
POST http://localhost:8000/api/raids/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "name": "Vampire Hunt",
  "dungeon": 3,
  "date": "2025-08-21",
  "success": false,
  "participations_create": [
    {"hunter_id": 2, "role": "Tank"},
    {"hunter_id": 3, "role": "DPS"}
  ]
}

###
PUT http://localhost:8000/api/raids/75f2c13e-2cc6-4f20-8e7a-315791a9790b/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "name": "Dragon Hunt Extreme",
    "dungeon": 11,
    "date": "2023-06-02",
    "success": false,
    "participations": [
        {"hunter_id": 36, "role": "DPS"},
        {"hunter_id": 38, "role": "Tank"}
    ]
}

###
DELETE http://localhost:8000/api/raids/75f2c13e-2cc6-4f20-8e7a-315791a9790b/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}


### ===== RAID PARTICIPATIONS =====
GET http://localhost:8000/api/raid-participations/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET http://localhost:8000/api/raid-participations/43/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

###
POST http://localhost:8000/api/raid-participations/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "raid_id": "64caaeb8-0a78-46f7-89d1-2c905c5297a8",
    "hunter_id": 36,
    "role": "Healer"
}

###
PUT http://localhost:8000/api/raid-participations/46/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "raid_id": "64caaeb8-0a78-46f7-89d1-2c905c5297a8",
    "hunter_id": 37,
    "role": "Healer"
}

###
DELETE http://localhost:8000/api/raid-participations/46/ HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}


