POST http://localhost:8000/api/hunters/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTk3Mjk3LCJpYXQiOjE3NTUxOTM2OTcsImp0aSI6ImY1M2YyZDE2MTk3MDQwZGVhZWRlZDZlNmVjMmQ2OGNjIiwidXNlcl9pZCI6IjMzIn0.HLjL6E91AmrUbVukuEfGxFxXgdGOS6hS1cxa82m4Zb4

{
    "first_name": "David", 
    "last_name": "Garcia", 
    "username": "david", 
    "password": "test", 
    "email": "0G2c4@example.com",
    "rank": "A",
    "skills": [41],
    "guild": 9
}

###

POST http://localhost:8000/api/raids/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTk4MzAxLCJpYXQiOjE3NTUxOTQ3MDEsImp0aSI6IjAzOTlhN2MxOGZkZDQ5ODE4NmNiZDBjMGFmNGFiNWYzIiwidXNlcl9pZCI6IjMzIn0.z2q_Rp9sQuNMabJq1ajT0c4m31JV6lotwhVzY0hepCg

{
    "name": "Raid 1",
    "dungeon": 6,
    "date": "2023-06-01",
    "success": false,
    "participations": [
        {"hunter_id": 18, "role": "Healer"},
        {"hunter_id": 20, "role": "Healer"}
    ]
}


###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}