POST http://localhost:8000/api/hunters/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjM4OTAzLCJpYXQiOjE3NTUyMzUzMDMsImp0aSI6IjI3MDVjMThlMjNjODRiNDBhYjFmMmU0OWE3Njc0YWY2IiwidXNlcl9pZCI6IjMzIn0.gWXAzxXeaJDtqj_Sc-q6-32Lmx0tX8bhBm8-Szi9LDc

{
    "first_name": "CJ", 
    "last_name": "Ping", 
    "username": "cjping", 
    "password": "test", 
    "email": "ping@example.com",
    "rank": "E",
    "skills": [41],
    "guild": null
}

###

POST http://localhost:8000/api/raids/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjI5NjE2LCJpYXQiOjE3NTUyMjYwMTYsImp0aSI6IjQ5OWNiZTMwNTMxZDRhNDA4Y2I1NTU0NGFiMWM2MzQwIiwidXNlcl9pZCI6IjM2In0.HN7_k2lpjrO24zO1zFKJurB-pzsx3c7ixZiuC2JdwS4

{
    "name": "China Raid",
    "dungeon": 8,
    "date": "2023-06-01",
    "success": false,
    "participations": [
        {"hunter_id": 19, "role": "DPS"},
        {"hunter_id": 21, "role": "Healer"}
    ]
}


###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "scottlaura",
    "password": "password123"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "kurtamodia",
    "password": "kmgwapo12"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8000/api/raid-participations/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjM5NDcyLCJpYXQiOjE3NTUyMzU4NzIsImp0aSI6IjU2MjZlZTgyNmI0NzQ4OWZhMTNjNGQ0NTc1NjY3YjJlIiwidXNlcl9pZCI6IjI1In0.OSzUuAs6qng1LbeRJKJ8HfbWOe3CmVozXgLcov2gSW8


###

POST http://localhost:8000/api/guild-invite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjM5MDM4LCJpYXQiOjE3NTUyMzU0MzgsImp0aSI6ImU1MzI0Yjg3OGJkNjRlNTFiNzdhMjEyN2M5NWU2OGNiIiwidXNlcl9pZCI6IjM2In0.-zbsPzGbDHMexFbYwek1jSrkbEugt3P2tWaKl3pxpdA

{
    "guild_id": 10,
    "hunter_id": 38
}