version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis

  web:
    build: .
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: 1
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_ENGINE: ${DB_ENGINE}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis
    command: python manage.py test

  celery:
    build: .
    volumes:
      - ./hunter-api:/app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: 1
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_ENGINE: ${DB_ENGINE}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis
    command: celery -A hunter_api worker --loglevel=info
