version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    environment:
      REDIS_URL: ${REDIS_URL}
    volumes:
      - redis_data:/data

  web:
    build: .
    volumes:
      - ./hunter-api:/app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: 1
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_ENGINE: django.db.backends.postgresql
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis
    command: python manage.py test

volumes:
  postgres_data:
  redis_data:
