services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # keep DB in memory to reduce disk I/O and speed up tests
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --save "" --appendonly no
    tmpfs:
      - /data

  web:
    build: .
    volumes:
      - ./hunter-api:/app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: 1
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_ENGINE: django.db.backends.postgresql
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: python manage.py test --noinput --parallel=1

volumes: {}
