services:
  web:
    build: .
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      REDIS_URL: "${REDIS_URL}"
    command: python manage.py test
    depends_on:
      - db
      - redis
