# Generated by Django 5.2.5 on 2025-08-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hunter',
            options={'verbose_name': 'Hunter', 'verbose_name_plural': 'Hunters'},
        ),
    ]
