# Generated by Django 5.2.5 on 2025-08-19 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hunter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='raid_id',
        ),
        migrations.AddField(
            model_name='raid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='raidparticipation',
            name='hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raidparticipation',
            name='raid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.raid'),
        ),
    ]
