# Generated by Django 5.2.5 on 2025-08-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_raid_raid_id_raid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidparticipation',
            name='damage_dealt',
        ),
        migrations.RemoveField(
            model_name='raidparticipation',
            name='healing_done',
        ),
    ]
