name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Dockerized tests
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up --build
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: 1
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_HOST: db
          DB_PORT: 5432
          DB_ENGINE: django.db.backends.postgresql
          REDIS_URL: redis://redis:6379/1

      - name: Shut down containers
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v
