name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and start containers (CI override)
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Run migrations
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm web python manage.py migrate --noinput

      - name: Run Django tests
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm web python manage.py test

      - name: Shut down
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v
